development/angular/client-side/src/app/app.component.ts
development/angular/client-side/src/app/app.service.ts
development/angular/client-side/src/app/reports/attendance/student-attendance/student-attendance.component.ts
development/angular/client-side/src/app/reports/attendance/teacher-attendance/teacher-attendance.component.ts
development/angular/client-side/src/app/reports/exception-list/pat-exception/pat-exception.component.ts
development/angular/client-side/src/app/reports/exception-list/sat-exception/semester-exception.component.ts
development/angular/client-side/src/app/reports/exception-list/student-attendance-exception/student-attendance-exception.component.ts
development/angular/client-side/src/app/reports/exception-list/teacher-attendance-exception/teacher-attendance-exception.component.ts
development/angular/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.ts
development/angular/client-side/src/app/reports/school-infra/udise-report/udise-report.component.ts
development/angular/client-side/src/app/reports/student-performance/pat-report/pat-report.component.ts
development/angular/client-side/src/app/reports/student-performance/sat-report/sat-report.component.ts
development/angular/client-side/src/app/reports/student-performance/sem-view/sem-view.component.ts

C qube release qa

---

development/angular/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.ts
development/angular/client-side/src/app/reports/student-performance/sat-heat-chart/sat-heat-chart.component.ts
development/angular/server-side/src/api/controller/patRoutes/heatChart/helper.js

Heatmap issue resolved

---

development/angular/client-side/src/app/app-routing.module.ts
development/angular/client-side/src/app/auth.guard.ts

C qube test

---

development/admin/client-side/src/app/home/home.component.html
development/angular/client-side/src/app/containers/home-usecase-two/home-usecase-two.component.css
development/angular/client-side/src/app/containers/home-usecase-two/home-usecase-two.component.html
development/angular/client-side/src/app/containers/home/home.component.css
development/angular/client-side/src/app/containers/home/home.component.html
development/angular/client-side/src/environments/environment.ts

Version and release date updated

Version and release date updated

---

development/nifi/diksha_transformer.xml

updated nifi attribute in diksha workflow, which was causing inconsistent status update in diksha api meta

updated nifi attribute in diksha workflow.

---

development/angular/client-side/src/app/home/home.component.css
development/angular/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.css
development/angular/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.html
development/angular/client-side/src/styles.css

Fixed header applied on Infra map

Fixed header applied on Infra map

---

development/angular/client-side/src/app/reports/student-performance/sat-heat-chart/sat-heat-chart.component.css

Cqube new UI changes implemented

Cqube new UI changes implemented

---

development/angular/client-side/src/app/common/multi-select/multi-select.component.css
development/angular/client-side/src/app/reports/composit/composit-report/composit-report.component.html
development/angular/client-side/src/app/reports/composit/composit-report/composit-report.component.ts
development/angular/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.html
development/angular/client-side/src/app/reports/diksha/tpd/diksha-tpd-course-progress/diksha-tpd-content-progress.component.html
development/angular/client-side/src/app/reports/diksha/tpd/diksha-tpd-course-progress/diksha-tpd-content-progress.component.ts
development/angular/client-side/src/app/reports/exception-list/missing-data/missing-data.component.css
development/angular/client-side/src/app/reports/exception-list/pat-exception/pat-exception.component.html
development/angular/client-side/src/app/reports/exception-list/sat-exception/semester-exception.component.html
development/angular/client-side/src/app/reports/exception-list/student-attendance-exception/student-attendance-exception.component.html
development/angular/client-side/src/app/reports/exception-list/teacher-attendance-exception/teacher-attendance-exception.component.html
development/angular/client-side/src/app/reports/healthCard/health-card/health-card.component.css
development/angular/client-side/src/app/reports/healthCard/health-card/health-card.component.html
development/angular/client-side/src/app/reports/healthCard/health-card/health-card.component.ts
development/angular/client-side/src/app/reports/school-infra/school-infrastructure/school-infrastructure.component.ts
development/angular/client-side/src/app/reports/school-monitoring/crc-report/crc-report.component.css
development/angular/client-side/src/app/reports/school-monitoring/crc-report/crc-report.component.html
development/angular/client-side/src/app/reports/school-monitoring/crc-report/crc-report.component.ts
development/angular/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.css
development/angular/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.html
development/angular/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.html
development/angular/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.ts
development/angular/client-side/src/app/reports/student-performance/sat-heat-chart/sat-heat-chart.component.css
development/angular/client-side/src/app/reports/student-performance/sat-heat-chart/sat-heat-chart.component.html
development/angular/client-side/src/app/reports/student-performance/sat-heat-chart/sat-heat-chart.component.ts
development/angular/client-side/src/app/reports/telemetry/telemetry-data/telemetry-data.component.css
development/angular/client-side/src/app/reports/telemetry/telemetry-data/telemetry-data.component.html
development/angular/client-side/src/styles.css

C qube UI ux

---

development/angular/client-side/src/app/reports/diksha/bar-chart/bar-chart.component.ts
development/angular/client-side/src/app/reports/healthCard/health-card/health-card.component.ts
development/angular/client-side/src/app/reports/school-infra/udise-report/udise-report.component.css
development/angular/client-side/src/styles.css

UI issues fixed

---

development/angular/client-side/src/app/home/home.component.html
development/angular/client-side/src/app/home/home.component.ts
development/angular/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.ts
development/angular/client-side/src/app/reports/school-infra/udise-report/udise-report.component.ts
development/angular/client-side/src/app/reports/student-performance/pat-report/pat-report.component.ts
development/angular/client-side/src/app/reports/student-performance/sat-report/sat-report.component.ts

Download issue for map legend range is resolved

Download issue for map legend range is resolved

---

development/angular/client-side/src/app/containers/home/home.component.css
development/angular/client-side/src/app/containers/home/home.component.ts
development/angular/client-side/src/app/reports/school-infra/school-infrastructure/school-infrastructure.component.css
development/angular/client-side/src/app/services/theme.service.ts
development/angular/client-side/src/styles.css

css themes applied for 4k screens as well

css themes aplied for 4k screens as well

---

development/ui/dashboard_ui/educational_new_theme/client-side/src/app/dashboards/group-dashboards/compostie-dashboard/compostie-dashboard.component.html
development/ui/dashboard_ui/educational_new_theme/client-side/src/app/dashboards/group-dashboards/crc-dashboard/crc-dashboard.component.html
development/ui/dashboard_ui/educational_new_theme/client-side/src/app/dashboards/group-dashboards/data-sources.service.ts
development/ui/dashboard_ui/educational_new_theme/client-side/src/app/dashboards/group-dashboards/etb-dashboard/etb-dashboard.component.html
development/ui/dashboard_ui/educational_new_theme/client-side/src/app/dashboards/group-dashboards/exception-dashboard/exception-dashboard.component.html
development/ui/dashboard_ui/educational_new_theme/client-side/src/app/dashboards/group-dashboards/infrastructure-dashboard/infrastructure-dashboard.component.html
development/ui/dashboard_ui/educational_new_theme/client-side/src/app/dashboards/group-dashboards/progress-card-dashboard/progress-card-dashboard.component.html
development/ui/dashboard_ui/educational_new_theme/client-side/src/app/dashboards/group-dashboards/std-performance-dashboard/std-performance-dashboard.component.html
development/ui/dashboard_ui/educational_new_theme/client-side/src/app/dashboards/group-dashboards/sttendance-dashboard/sttendance-dashboard.component.html
development/ui/dashboard_ui/educational_new_theme/client-side/src/app/dashboards/group-dashboards/telemetry-dashboard/telemetry-dashboard.component.html
development/ui/dashboard_ui/educational_new_theme/client-side/src/app/dashboards/group-dashboards/tpd-dashboard/tpd-dashboard.component.html
development/ui/dashboard_ui/educational_old_theme/client-side/src/app/containers/home-usecase-two/home-usecase-two.component.html
development/ui/dashboard_ui/educational_old_theme/client-side/src/app/containers/home-usecase-two/home-usecase-two.component.ts
development/ui/dashboard_ui/educational_old_theme/client-side/src/app/containers/home/home.component.html
development/ui/dashboard_ui/educational_old_theme/client-side/src/app/containers/home/home.component.ts
development/ui/dashboard_ui/educational_old_theme/client-side/src/app/dashboards/education_usecase/dashboard.component.html
development/ui/dashboard_ui/educational_old_theme/client-side/src/app/dashboards/education_usecase/dashboard.component.ts
development/ui/dashboard_ui/educational_old_theme/client-side/src/app/dashboards/test_usecase/dashboard-clone.component.html
development/ui/dashboard_ui/educational_old_theme/client-side/src/app/dashboards/test_usecase/dashboard-clone.component.ts
development/ui/dashboard_ui/educational_old_theme/client-side/src/app/dashboards/usecase-three/usecase-three.component.html
development/ui/dashboard_ui/educational_old_theme/client-side/src/app/dashboards/usecase-three/usecase-three.component.ts
development/ui/dashboard_ui/educational_old_theme/client-side/src/app/dashboards/usecase-two/usecase-two.component.html
development/ui/dashboard_ui/educational_old_theme/client-side/src/app/dashboards/usecase-two/usecase-two.component.ts

C qube usecase test

---

development/angular/client-side/src/app/auth.guard.ts
development/angular/server-side/src/api/controller/attendanceRoutes/sttendance-line-chart/onSelectDistrict.js

after login page not showing issue resolved

after login page not showing issue resolved

---

development/node_api/dashboard_api/server-side/src/api/controller/progressCard/metadata.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/progressCard/progress-card/progress-card.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/progressCard/progress-card/progress-card.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-heat-chart/sat-heat-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-heat-chart/sat-heat-chart.component.ts

PAT SAT and progressCard tasks completed

PAT SAT and progressCard tasks completed

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-completion-percentage/diksha-tpd-completion.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts

Diksha TPD cource deselection task completed

Diksha TPD cource deselection task completed

---

development/ui/admin_ui/client-side/src/app/components/users/change-password/change-password.component.ts
development/ui/admin_ui/client-side/src/app/components/users/create-user/create-user.component.ts

admin-dashboard issue resolved

admin-dashboard issue resolved

---

development/ui/admin_ui/client-side/src/app/components/users/change-password/change-password.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-table/diksha-table.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-table/diksha-table.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/usage-by-textbook-content/usage-by-textbook-content.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/usage-by-textbook-content/usage-by-textbook-content.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/users/change-password/change-password.component.ts

PAT map subject dropdown changes done

PAT map subject dropdown changes done

---

development/ui/admin_ui/client-side/src/app/components/data-replay/data-replay.component.ts

loader loding issue resolved for data-replay

loader loding issue resolved for data-replay

---

development/node_api/admin_api/server-side/src/api/controller/data-replay/dikshaTPD_ETB_data_input.js
development/ui/admin_ui/client-side/src/app/components/data-replay/data-replay.component.ts

data-replay TPD ETB isses resolved

data-replay TPD ETB isses resolved

---

development/ui/admin_ui/client-side/src/app/components/data-replay/data-replay.component.ts
development/ui/admin_ui/client-side/src/app/home/home.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.html

cQube- release-3.2

---

development/ui/admin_ui/client-side/src/app/components/diksha-config/diksha-config.component.css
development/ui/admin_ui/client-side/src/app/components/diksha-config/diksha-config.component.html
development/ui/admin_ui/client-side/src/app/components/diksha-config/diksha-config.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.ts

Diksha-config page issues resolved

Diksha-config page issues resolved

---

development/node_api/admin_api/server-side/src/api/controller/data-replay/dikshaConfig.js
development/node_api/admin_api/server-side/src/api/controller/data-replay/dikshaTPD_ETB_data_input.js
development/ui/admin_ui/client-side/src/app/components/diksha-config/diksha-config.component.html
development/ui/admin_ui/client-side/src/app/components/diksha-config/diksha-config.component.ts

Diksha-config issue fixed

---

development/ui/admin_ui/client-side/src/app/components/diksha-config/diksha-config.component.ts

diksha-config response time issue fixed

diksha-config response time issue fixed

---

development/node_api/dashboard_api/server-side/src/api/controller/diksha/content-usage-pie-chart/distMeta.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/content-usage-pie-chart/distWise.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/content-usage-pie-chart/stateData.js
development/node_api/dashboard_api/server-side/src/api/router.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/tpd-dashboard/tpd-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.spec.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha.module.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/services/content-usage-pie.service.ts

Content Usage Pie chart Demo

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance/student-attendance.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/teacher-attendance/teacher-attendance.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/student-attendance-exception/student-attendance-exception.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/teacher-attendance-exception/teacher-attendance-exception.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/udise-report/udise-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-report/sat-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/services/map-services/maps.service.ts

 Maps Drag and zoom changed

---

development/node_api/dashboard_api/server-side/src/api/controller/diksha/content-usage-pie-chart/distMeta.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/content-usage-pie-chart/distWise.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/content-usage-pie-chart/stateData.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/map-report/etb-map-report/distWise.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/map-report/tpd-map-report/distWise.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/services/map-services/maps.service.ts

Added Pie Chart for diksha content Usage

Added Pie Chart for diksha content Usage

---

development/node_api/dashboard_api/server-side/src/api/controller/diksha/content-usage-pie-chart/distMeta.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/etb-dashboard/etb-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/tpd-dashboard/tpd-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts

Error Solved

---

development/node_api/dashboard_api/server-side/src/api/controller/diksha/content-usage-pie-chart/distMeta.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.ts

Diksha grouped bar chart modified

Diksha grouped bar chart modified

---

development/ui/dashboard_ui/education_usecase/client-side/package.json
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.ts

Added Expected Enrollment bar in grouped chart bar

Added Expected Enrollment bar in grouped chart bar

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.ts

Added Legend and tooltip to TPD/ETB map

Added Legend and tooltip to TPD/ETB map

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/app.service.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.ts

Tooltip and download button Added to Diskha map

Tooltip and download button Added to Diskha map

---

development/node_api/dashboard_api/server-side/src/api/controller/diksha/average-time-spend-on-course/distWise.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/average-time-spend-on-course/stateData.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/total-content-play-over-years/stateData.js
development/node_api/dashboard_api/server-side/src/api/router.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/tpd-dashboard/tpd-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.spec.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/bar-chart/bar-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha.module.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/total-content-play-over-years/total-content-play-over-years.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/total-content-play-over-years/total-content-play-over-years.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/services/average-time-spend-bar.service.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/services/total-content-play-line-cahrt.service.ts

Added Line Chart and Bar chart for Average Time spend on course

Added Line Chart and Bar chart for Average Time spend on course

---

development/node_api/dashboard_api/server-side/src/api/controller/diksha/map-report/per-capita-report/stateData.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/total-content-play-over-years/distMeta.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/total-content-play-over-years/distWise.js
development/node_api/dashboard_api/server-side/src/api/router.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/app.service.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/bar-chart/bar-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/total-content-play-over-years/total-content-play-over-years.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/total-content-play-over-years/total-content-play-over-years.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/services/total-content-play-line-cahrt.service.ts

Added Total enrollment over years with real data

Added Total enrollment over years with real data

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/etb-dashboard/etb-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/tpd-dashboard/tpd-dashboard.component.html

Added headings for Reports

---

development/node_api/dashboard_api/server-side/src/api/lib/uploadFile.js

Azure confingure changes

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.ts

Enrollment X axis date point intervel

Enrollment X axis date point intervel

---

development/node_api/admin_api/server-side/src/api/lib/readFiles.js

Azure configuration on admin

---

development/node_api/admin_api/server-side/src/api/controller/users/addUser.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/tpd-enroll-completion/distWise.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.ts

Multi bar chart with expected enrolled bar

Multi bar chart with expected enrolled bar

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/etb-dashboard/etb-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/etb-dashboard/etb-dashboard.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/exception-dashboard/exception-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/exception-dashboard/exception-dashboard.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/infrastructure-dashboard/infrastructure-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/infrastructure-dashboard/infrastructure-dashboard.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/progress-card-dashboard/progress-card-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/progress-card-dashboard/progress-card-dashboard.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/std-performance-dashboard/std-performance-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/std-performance-dashboard/std-performance-dashboard.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/sttendance-dashboard/sttendance-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/sttendance-dashboard/sttendance-dashboard.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/telemetry-dashboard/telemetry-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/telemetry-dashboard/telemetry-dashboard.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/tpd-dashboard/tpd-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/tpd-dashboard/tpd-dashboard.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/reportHeading.config.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.html

Report Names configuration

---

development/node_api/dashboard_api/server-side/src/api/controller/diksha/diksha-bar-chart.js
development/ui/admin_ui/client-side/src/app/home/home.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/app.service.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/compostie-dashboard/compostie-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/compostie-dashboard/compostie-dashboard.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/etb-dashboard/etb-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/tpd-dashboard/tpd-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-bar-chart/diksha-bar-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-chart/diksha-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.ts

Bug fixes for 3.3 release

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.ts

small changes on multibar char

small changes on multibar chart

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/description.config.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/etb-dashboard/etb-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/tpd-dashboard/tpd-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.html

Report description added

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/description.config.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/etb-dashboard/etb-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/tpd-dashboard/tpd-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.html

cQube development

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/description.config.ts

Changed Discription for per capita

Changed Discription for per capita

---

development/ui/dashboard_ui/education_usecase/client-side/package.json
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.ts

Added state along with District download in User Engagement report

Added state along with District download in User Engagement report

---

development/datasource/cQube_data_storage/nifi/cQube_data_storage.xml

updated the property of fetch_files_from_emission_dir processor

updated the fetchfile property

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/app.service.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.ts

Changed Per capita report UI and ToolTip

Changed Per capita report UI and ToolTip

---

development/ui/dashboard_ui/education_usecase/client-side/package.json
development/ui/dashboard_ui/education_usecase/client-side/src/app/app.module.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/total-content-play-over-years/total-content-play-over-years.component.ts

Bug Retified in per capita

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/app.service.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.ts

Per Capita bug fixed

---

development/node_api/dashboard_api/server-side/src/api/controller/diksha/diksha-bar-chart.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/enrollment-progress/distWise.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/tpd-enroll-completion/blockWise.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/tpd-enroll-completion/distWise.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/tpd-enroll-completion/programData.js
development/node_api/dashboard_api/server-side/src/api/router.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.css
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-heat-chart/sat-heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/services/diksha-report.service.ts
development/ui/dashboard_ui/education_usecase/client-side/src/styles.css

multi bar chart drop down with search added

multi bar chart drop down with search added

---

development/node_api/dashboard_api/server-side/src/api/controller/diksha/tpd-enroll-completion/clusterWise.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/tpd-enroll-completion/distWise.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/tpd-enroll-completion/programData.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/app.service.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.css
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts

Multi bar chart dropdown bug fixed

Multi bar chart dropdown bug fixed

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/bar-chart/bar-chart.component.ts

bug in user engagment bar chart is rectified

bug in user engagment bar chart is rectified

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.ts

User onbording report bug fixed

User onbording report bug fixed

---

development/node_api/dashboard_api/server-side/src/api/controller/diksha/tpd-enroll-completion/schoolWise.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/bar-chart/bar-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.ts

Bug fixed in user engagment report

Bug fixed in user engagment report

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/total-content-play-over-years/total-content-play-over-years.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/styles.css

4k resolution ui changes

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/etb-dashboard/etb-dashboard.component.css
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/reportHeading.config.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/bar-chart/bar-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.html

4k resulotion UI fixed for Pie chat and TPD map legands

4k resulotion UI fixed for Pie chat and TPD map legands

---

development/node_api/dashboard_api/server-side/src/api/controller/diksha/tpd-enroll-completion/distWise.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/tpd-enroll-completion/programData.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.ts

bugs fixed for relese for 3.3 patch

bugs fixed for relese for 3.3 patch

---

development/node_api/dashboard_api/server-side/src/api/controller/diksha/tpd-enroll-completion/distWise.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/etb-dashboard/etb-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/tpd-dashboard/tpd-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.ts

Users Engagment download bug fixed

Users Engagment download bug fixed

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/etb-dashboard/etb-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/etb-dashboard/etb-dashboard.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/tpd-dashboard/tpd-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/tpd-dashboard/tpd-dashboard.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.html

changed ids for tpd and etb cards

changed ids for tpd and etb cards

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/bar-chart/bar-chart.component.ts

User Engagment report metrics changed from Minutes to Hours

User Engagment report metrics changed from Minutes to Hours

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/app.service.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/common/multi-select/multi-select.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.ts

ETB and TPD gps learning map report legend chnaged

ETB and TPD gps learning map report legend chnaged

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/composit/composit-report/composit-report.component.css
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/composit/composit-report/composit-report.component.html

id changed in crc report

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/composit/composit-report/composit-report.component.css
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.ts

Removed Actual user from footer in per capita map report

Removed Actual user from footer in per capita map report

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.ts

Percapita tool tip and user onbording xAxis changes updated

Percapita tool tip and user onbording xAxis changes updated

---

development/node_api/dashboard_api/server-side/src/api/controller/diksha/tpd-enroll-completion/certificateMeta.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/tpd-enroll-completion/distWise.js
development/node_api/dashboard_api/server-side/src/api/router.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.css
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/services/diksha-report.service.ts

added condition to hide report if Expected user is not provided

added condition to hide report if Expected user is not provided

---

development/node_api/dashboard_api/server-side/src/api/controller/diksha/tpd-enroll-completion/distWise.js

multi bar chart file path changed

multi bar chart file path changed

---

development/node_api/dashboard_api/server-side/src/api/controller/diksha/enrollment-progress/allCourse.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/enrollment-progress/allDistCollection.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/enrollment-progress/distWise.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/enrollment-progress/programData.js
development/node_api/dashboard_api/server-side/src/api/controller/diksha/enrollment-progress/programWiseCollection.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.ts

3.3 patch 2 bugs fixed

---

development/ui/admin_ui/client-side/src/app/home/home.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.html

patch Relese date changed

---

development/node_api/admin_api/server-side/src/api/controller/statistics/summary.js
development/ui/admin_ui/client-side/src/app/components/summary-statisticts/summary-statisticts.component.html
development/ui/admin_ui/client-side/src/app/components/summary-statisticts/summary-statisticts.component.ts
development/ui/admin_ui/client-side/src/app/services/summary.service.ts

Static summary table added for Diksha

Static summary table added for Diksha

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/styles.css

multi bar chart responsive changes done for scroll bar

multi bar chart responsive changes done for scroll bar

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.html

Bugs for 3.3 release patch 2 user onbording report fixed

Bugs for 3.3 release patch 2 user onbording report fixed

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.ts

Bug fixed for User Onbording report release 3.3 patch 2

Bug fixed for User Onbording report release 3.3 patch 2

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/dashboard-module.module.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/common-dashboard/common-dashboard.component.css
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/common-dashboard/common-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/common-dashboard/common-dashboard.component.spec.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/common-dashboard/common-dashboard.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/tpd-dashboard/tpd-dashboard.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance/student-attendance.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/teacher-attendance/teacher-attendance.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/udise-report/udise-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-report/sat-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/environments/environment.ts
development/ui/dashboard_ui/education_usecase/client-side/src/styles.css

added new common compnent and removed water mark

added new common compnent and removed water mark

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/app.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/app.service.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/keycloak-security.service.ts
development/ui/dashboard_ui/education_usecase/client-side/src/environments/environment.ts

Envirolment property name changed

Envirolment property name changed

---

development/node_api/admin_api/server-side/src/api/controller/users/addUser.js
development/node_api/dashboard_api/server-side/src/api/controller/users/logIn.js
development/node_api/dashboard_api/server-side/src/api/middleware/check-auth.js
development/node_api/dashboard_api/server-side/src/api/router.js
development/ui/admin_ui/client-side/src/environments/environment.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/app.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/app.service.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/home-page/home-page.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/home-page/home-page.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/keycloak-security.service.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/services/login.service.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/signin/signin.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/environments/environment.ts

changed environment property name

changed environment property name

---

development/ui/admin_ui/client-side/package.json
development/ui/admin_ui/client-side/src/app/app.component.ts
development/ui/admin_ui/client-side/src/app/app.module.ts
development/ui/admin_ui/client-side/src/app/app.service.ts
development/ui/admin_ui/client-side/src/app/home/home.component.ts
development/ui/admin_ui/client-side/src/app/keycloak-security.service.ts
development/ui/dashboard_ui/education_usecase/client-side/package.json
development/ui/dashboard_ui/education_usecase/client-side/src/app/app.module.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/home-page/home-page.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/home-page/home-page.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/signin/signin.component.ts

Development of Access for admin console in state config is added

Development of Access for admin console in state config is added

---

development/node_api/admin_api/server-side/src/api/controller/keyclockDB/db.js
development/node_api/dashboard_api/server-side/src/api/controller/kekcloakDB/db.js

Remove unwanted code

---

development/node_api/admin_api/server-side/src/api/controller/users/addUser.js
development/node_api/dashboard_api/server-side/src/api/controller/users/keycloak-otp/state.js
development/node_api/dashboard_api/server-side/src/api/controller/users/logIn.js
development/node_api/dashboard_api/server-side/src/api/router.js
development/ui/admin_ui/client-side/src/app/home/home.component.html
development/ui/admin_ui/client-side/src/environments/environment.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/services/login.service.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/signin/signin.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/signin/signin.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/environments/environment.ts

3.4 version bugs fixed

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.ts

Added certificate bar for lower level selection for multibar chart

Added certificate bar for lower level selection for multibar chart

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/home-page/home-page.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/signin/signin.component.ts

state logout button fixed

---

development/ui/admin_ui/client-side/src/app/home/home.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/home-page/home-page.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/signin/signin.component.ts

3.4 release bug fixed

---

development/node_api/dashboard_api/server-side/src/api/controller/users/keycloak-otp/cqube.js
development/node_api/dashboard_api/server-side/src/api/controller/users/keycloak-otp/state.js

3.4 upgradation with state bug fixed

3.4 upgradation with state bug fixed

---

development/node_api/dashboard_api/server-side/src/api/controller/users/keycloak-otp/cqube.js
development/node_api/dashboard_api/server-side/src/api/controller/users/keycloak-otp/state.js

State to cQube && cQube to cQube upgradation bug fixed

State to cQube && cQube to cQube upgradation bug fixed

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/bar-chart/bar-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.ts

Multibar chart and user engagement report UI changes fixed

Multibar chart and user engagement report UI changes fixed

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.html

Added Breadcrum to Multibar chart

Added Breadcrum to Multibar chart

---

development/node_api/dashboard_api/server-side/src/api/controller/users/keycloak-otp/config.js
development/node_api/dashboard_api/server-side/src/api/controller/users/keycloak-otp/state.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.ts

Space reduced between bar and value

Space reduced between bar and value

---

development/node_api/dashboard_api/server-side/src/api/controller/users/keycloak-otp/state.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.ts

Multi Bar chart small values to show bar and expected bar value overlap fixed

Multi Bar chart small values to show bar and expected bar value overlap fixed

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/multi-bar-chart/multi-bar-chart.component.ts

User Progress report certificate bar color for district level changed

User Progress report certificate bar color for district level changed

---

development/node_api/admin_api/server-side/package.json
development/node_api/admin_api/server-side/src/index.js
development/node_api/dashboard_api/server-side/package.json
development/node_api/dashboard_api/server-side/src/index.js

vunerability bugs fixed

---

development/node_api/dashboard_api/server-side/src/index.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/app.service.ts

In Content Preference download report district name are arranged in Aplha order

In Content Preference download report district name are arranged in Aplha order

---

development/datasource/cQube_data_storage/nifi/cQube_data_storage.xml
development/datasource/datascience/nifi/datascience_transformer.xml
development/datasource/python/data_science_script/anomaly/anomalyDetectionUtils.py
development/node_api/dashboard_api/server-side/src/api/controller/DataScienceRoutes/anomalyRoutes/report_map/anomalyBlockWise.js
development/node_api/dashboard_api/server-side/src/api/controller/DataScienceRoutes/anomalyRoutes/report_map/anomalyClusterWise.js
development/node_api/dashboard_api/server-side/src/api/controller/DataScienceRoutes/anomalyRoutes/report_map/anomalyDistWise.js
development/node_api/dashboard_api/server-side/src/api/controller/DataScienceRoutes/anomalyRoutes/report_map/anomalySchoolWise.js
development/node_api/dashboard_api/server-side/src/api/controller/DataScienceRoutes/dropoutRoutes/report_map/dropoutBlockWise.js
development/node_api/dashboard_api/server-side/src/api/controller/DataScienceRoutes/dropoutRoutes/report_map/dropoutClusterWise.js
development/node_api/dashboard_api/server-side/src/api/controller/DataScienceRoutes/dropoutRoutes/report_map/dropoutDistWise.js
development/node_api/dashboard_api/server-side/src/api/controller/DataScienceRoutes/dropoutRoutes/report_map/dropoutSchoolWise.js
development/ui/dashboard_ui/datascience_usecase/client-side/src/app/reports/data-science/anomaly-report/anomaly-report.component.html
development/ui/dashboard_ui/datascience_usecase/client-side/src/app/reports/data-science/anomaly-report/anomaly-report.component.ts
development/ui/dashboard_ui/datascience_usecase/client-side/src/app/reports/data-science/dropout-report/dropout-report.component.html
development/ui/dashboard_ui/datascience_usecase/client-side/src/app/reports/data-science/dropout-report/dropout-report.component.ts
workflow_deploy/ansible/roles/datascience/tasks/main.yml
workflow_deploy/ansible/roles/nifi_params/templates/datascience_parameters.json.j2

Some expressions and links are modified in NiFi Processors and Code cleaned.

Datascience NiFi processor updated

---

development/node_api/dashboard_api/server-side/package.json
development/node_api/dashboard_api/server-side/src/api/controller/users/logIn.js
development/node_api/dashboard_api/server-side/src/index.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/total-content-play-over-years/total-content-play-over-years.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/styles.css

added loader to content preference and removed unused dependency

added loader to content preference and removed unused dependency

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.html

C qube development

---

development/node_api/dashboard_api/server-side/src/api/controller/users/changePassword.js

cQube 3.5 Change password defect

---

development/datasource/sat/nifi/sat_queries.json

added sat_meta_all query in sat_queries.json file

sat_queries meta all query

---

development/datasource/pat/nifi/pat_parameters.txt

at line number 271, spelling mistake nulll is replaced with null

Pat parameter null spelling mistake

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance/student-attendance.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/teacher-attendance/teacher-attendance.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/composit/composit-report/composit-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/composit/composit-report/composit-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/tpd/diksha-tpd-course-progress/diksha-tpd-content-progress.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/tpd/diksha-tpd-course-progress/diksha-tpd-content-progress.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/pat-exception/pat-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/sat-exception/semester-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/school-infrastructure/school-infrastructure.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/school-infrastructure/school-infrastructure.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/udise-report/udise-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/udise-report/udise-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-monitoring/crc-report/crc-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-monitoring/crc-report/crc-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-heat-chart/sat-heat-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-heat-chart/sat-heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-report/sat-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-report/sat-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/signin/signin.component.ts

added user level access

---

development/node_api/dashboard_api/server-side/src/api/controller/users/changePassword.js

Change password bug fixed

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance/student-attendance.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance/student-attendance.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/teacher-attendance/teacher-attendance.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/teacher-attendance/teacher-attendance.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/pat-exception/pat-exception.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/pat-exception/pat-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/sat-exception/semester-exception.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/sat-exception/semester-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/student-attendance-exception/student-attendance-exception.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/student-attendance-exception/student-attendance-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/teacher-attendance-exception/teacher-attendance-exception.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/teacher-attendance-exception/teacher-attendance-exception.component.ts

Added User Access level to Exception and Attendance Reports

Added User Access level to Exception and Attendance Reports

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance/student-attendance.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/teacher-attendance/teacher-attendance.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/composit/composit-report/composit-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/composit/composit-report/composit-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/tpd/diksha-tpd-course-progress/diksha-tpd-content-progress.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/tpd/diksha-tpd-course-progress/diksha-tpd-content-progress.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/pat-exception/pat-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/sat-exception/semester-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/student-attendance-exception/student-attendance-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/teacher-attendance-exception/teacher-attendance-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/school-infrastructure/school-infrastructure.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/school-infrastructure/school-infrastructure.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/udise-report/udise-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-monitoring/crc-report/crc-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-heat-chart/sat-heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-report/sat-report.component.ts

fixed user access level bugs for block and cluster level

fixed user access level bugs for block and cluster level

---

development/node_api/dashboard_api/server-side/src/api/controller/users/logIn.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/pat-exception/pat-exception.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/sat-exception/semester-exception.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/sat-exception/semester-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/student-attendance-exception/student-attendance-exception.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/student-attendance-exception/student-attendance-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/teacher-attendance-exception/teacher-attendance-exception.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/school-infrastructure/school-infrastructure.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/udise-report/udise-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-heat-chart/sat-heat-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-heat-chart/sat-heat-chart.component.ts

FIxed blockers for 3.6 release

FIxed blockers for 3.6 release

---

development/node_api/dashboard_api/server-side/src/api/controller/users/changePassword.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance-chart/student-attendance-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance-chart/student-attendance-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance/student-attendance.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/teacher-attendance/teacher-attendance.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/composit/composit-report/composit-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/composit/composit-report/composit-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/pat-exception/pat-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/sat-exception/semester-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/student-attendance-exception/student-attendance-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/teacher-attendance-exception/teacher-attendance-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/progressCard/progress-card/progress-card.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/progressCard/progress-card/progress-card.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/school-infrastructure/school-infrastructure.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-monitoring/crc-report/crc-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-monitoring/crc-report/crc-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-heat-chart/sat-heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-report/sat-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-trends-chart/sat-trends-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-trends-chart/sat-trends-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/telemetry/telemetry-data/telemetry-data.component.ts

bugs fixed for 3.6 release

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance-chart/student-attendance-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/usage-by-textbook-content/usage-by-textbook-content.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/udise-report/udise-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-heat-chart/sat-heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/signin/signin.component.ts

Access level button removed for default admin user login

Access level button removed for default admin user login

---

development/datasource/sat/nifi/sat_queries.json

'sat_meta_semester_last30','sat_meta_semester_last7','sat_meta_semester_all' these are added into sat_queries.json to generate sat_semester_metadata.json file.

Sat_queries.json updated

---

development/node_api/dashboard_api/server-side/src/api/controller/users/changePassword.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance/student-attendance.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/udise-report/udise-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/udise-report/udise-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-report/sat-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-report/sat-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/environments/environment.ts

Changed Functionality of blockwise button according to Level of selection

Changed Functionality of blockwise button according to Level of selection 

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance/student-attendance.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance/student-attendance.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/teacher-attendance/teacher-attendance.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/teacher-attendance/teacher-attendance.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/pat-exception/pat-exception.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/pat-exception/pat-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/sat-exception/semester-exception.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/sat-exception/semester-exception.component.ts

allBlock button funtionality changed according to lowe level selection in attandance report

AllBlock button funtionality changed according to lowe level selection in attandance report

---

workflow_deploy/ansible/roles/angular/templates/environment.prod_local.ts.j2
workflow_deploy/ansible/update_ui.yml
workflow_deploy/ansible/upgrade.yml
workflow_deploy/education_usecase/install_ui.sh
workflow_deploy/education_usecase/update_ui.sh
workflow_deploy/education_usecase/upgrade.sh

added " to the missing variables in env.prod files, Added hosts variable to upgradation files

changes in env and upgrade files

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/app.service.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/common/line-chart/line-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance/student-attendance.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance/student-attendance.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/teacher-attendance/teacher-attendance.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/composit/composit-report/composit-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/composit/composit-report/composit-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/pat-exception/pat-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/sat-exception/semester-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/student-attendance-exception/student-attendance-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/teacher-attendance-exception/teacher-attendance-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/school-infrastructure/school-infrastructure.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/udise-report/udise-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-monitoring/crc-report/crc-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-report/sat-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-trends-chart/sat-trends-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/environments/environment.ts

disabled all block and cluster button depends on selection

disabled all block and cluster button depends on selection

---

development/ui/admin_ui/client-side/src/app/components/data-replay/data-replay.component.ts
development/ui/admin_ui/client-side/src/app/home/home.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance/student-attendance.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/teacher-attendance/teacher-attendance.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/tpd/diksha-tpd-course-progress/diksha-tpd-content-progress.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/student-attendance-exception/student-attendance-exception.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-monitoring/crc-report/crc-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-monitoring/crc-report/crc-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.ts

CRC issue fixed

---

development/datasource/udise/nifi/udise_transformer.xml

removed generate flow processor which was causing queries execution when start udise tranformer

udise removed generate flow processor

---

development/node_api/dashboard_api/server-side/src/api/controller/users/logIn.js
development/ui/admin_ui/client-side/src/app/components/data-replay/data-replay.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance/student-attendance.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/student-attendance-exception/student-attendance-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-monitoring/crc-report/crc-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-report/sat-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/users/change-password/change-password.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/environments/environment.ts

fixed Acess level when userLocation is wrong id or null

fixed Acess level when userLocation is wrong id or null

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/crc-dashboard/crc-dashboard.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/student-attendance-exception/student-attendance-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/teacher-attendance-exception/teacher-attendance-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-heat-chart/sat-heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/environments/environment.ts

Block names are repeating in teacher exception fixed

 Block names are repeating in teacher exception fixed

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.css
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.ts

fixed new requirement bugs 

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.ts

Removed Access button in pat reports

Removed Access button in pat reports 

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/school-infrastructure/school-infrastructure.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/school-infrastructure/school-infrastructure.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-monitoring/crc-report/crc-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.css
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.ts

fixed pat report year and month dropdown issue

fixed pat report year and month dropdown issue

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.ts

pat year and month  drop down issue fixed

pat year and month  drop down issue fixed

---

development/node_api/dashboard_api/server-side/src/api/controller/users/logIn.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/tpd/diksha-tpd-course-progress/diksha-tpd-content-progress.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/pat-exception/pat-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/sat-exception/semester-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/student-attendance-exception/student-attendance-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/teacher-attendance-exception/teacher-attendance-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-monitoring/crc-report/crc-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.ts

School level access added in exception, multibar chart, pat lo report

School level access added in exception, multibar chart, pat lo report

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/composit/composit-report/composit-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/school-infrastructure/school-infrastructure.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-monitoring/crc-report/crc-report.component.ts

Added school level access in crc, infra composite , composte reports

Added school level access in crc, infra composite , composte reports

---

development/node_api/dashboard_api/server-side/src/api/controller/diksha/tpd-heatChart/schoolWise.js
development/node_api/dashboard_api/server-side/src/api/controller/patRoutes/heatChart/schoolWise.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/tpd/diksha-tpd-course-progress/diksha-tpd-content-progress.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-heat-chart/sat-heat-chart.component.ts

Added school level access in sat, pat heat chart and diksha course progress

Added school level access in sat, pat heat chart and diksha course progress 

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/teacher-attendance/teacher-attendance.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/composit/composit-report/composit-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/composit/composit-report/composit-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/tpd/diksha-tpd-course-progress/diksha-tpd-content-progress.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/tpd/diksha-tpd-course-progress/diksha-tpd-content-progress.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/pat-exception/pat-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-heat-chart/sat-heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-report/sat-report.component.ts

school level access defects fixed

school level access defects fixed

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance/student-attendance.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance/student-attendance.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/teacher-attendance/teacher-attendance.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/teacher-attendance/teacher-attendance.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/composit/composit-report/composit-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/tpd/diksha-tpd-course-progress/diksha-tpd-content-progress.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/usage-by-textbook-content/usage-by-textbook-content.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/pat-exception/pat-exception.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/pat-exception/pat-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/sat-exception/semester-exception.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/sat-exception/semester-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/student-attendance-exception/student-attendance-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/teacher-attendance-exception/teacher-attendance-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/school-infrastructure/school-infrastructure.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/school-infrastructure/school-infrastructure.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/udise-report/udise-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/udise-report/udise-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-monitoring/crc-report/crc-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-monitoring/crc-report/crc-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/heat-chart/heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.css
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-heat-chart/sat-heat-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-report/sat-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-report/sat-report.component.ts

footer hidded for school level user

footer hidded for school level user

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance/student-attendance.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.css
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/infra-map-visualisation/infra-map-visualisation.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/school-infrastructure/school-infrastructure.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/styles.css

Fixed multibar chart issue

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/average-time-spend-bar/average-time-spend-bar.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-bar-chart/diksha-bar-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-bar-chart/diksha-bar-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-table/diksha-table.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-table/diksha-table.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-usage-by-text-book/diksha-usage-by-text-book.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-usage-by-text-book/diksha-usage-by-text-book.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/enrollment-progress/enrollment-progress.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-per-capita/etb-per-capita.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/etb-total-content-plays/etb-total-content-plays.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/map-reports/tpd-total-content-plays/tpd-total-content-plays.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/tpd/diksha-tpd-course-progress/diksha-tpd-content-progress.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/usage-by-textbook-content/usage-by-textbook-content.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/sat-exception/semester-exception.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-infra/school-infrastructure/school-infrastructure.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.ts

school level defects fixed

---

development/ui/admin_ui/client-side/src/app/components/users/change-password/change-password.component.ts
development/ui/admin_ui/client-side/src/environments/environment.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-table/diksha-table.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/diksha-tpd-enrollment-and-completion/diksha-tpd-enrollment.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/total-content-play-over-years/total-content-play-over-years.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/total-content-play-over-years/total-content-play-over-years.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/usage-by-textbook-content/usage-by-textbook-content.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/usage-by-textbook-content/usage-by-textbook-content.component.ts

change Password fixed

---

development/node_api/dashboard_api/server-side/src/api/controller/users/logIn.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/content-usage-pie-chart/content-usage-pie-chart.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/usage-by-textbook-content/usage-by-textbook-content.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/diksha/usage-by-textbook-content/usage-by-textbook-content.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/student-attendance-exception/student-attendance-exception.component.ts

pie chart issue fixed

---

development/node_api/dashboard_api/server-side/src/api/controller/users/changePassword.js
development/node_api/dashboard_api/server-side/src/api/controller/users/logIn.js
development/ui/admin_ui/client-side/src/app/components/users/change-password/change-password.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.ts

change password and pat lo loadder issue fixed

change password and pat lo loadder issue fixed

---

development/ui/admin_ui/client-side/src/app/components/users/change-password/change-password.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.css
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.ts

change password routing fixed

---

development/ui/admin_ui/client-side/src/app/home/home.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.html

Release date changed

---

development/ui/admin_ui/client-side/src/app/components/users/change-password/change-password.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/services/map-services/maps.service.ts

Marker and LO reports fixed

---

development/datasource/sat/nifi/sat_parameters.txt

Updated the Jolt spec

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/sat-report/sat-report.component.ts

Pat grade issue fixed

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-report/pat-report.component.ts

pat map issue fixed

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/pat-exception/pat-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/sat-exception/semester-exception.component.ts

Sat and Pat Tool tip issue fixed

Sat and Pat Tool tip issue fixed

---

development/node_api/dashboard_api/server-side/package.json
development/node_api/dashboard_api/server-side/src/api/lib/uploadFile.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/student-attendance-exception/student-attendance-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/teacher-attendance-exception/teacher-attendance-exception.component.ts

telemetry issue fixed

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/student-attendance-exception/student-attendance-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/teacher-attendance-exception/teacher-attendance-exception.component.ts

Sat and Pat issue fixed

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/student-attendance-exception/student-attendance-exception.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/exception-list/teacher-attendance-exception/teacher-attendance-exception.component.ts

Sat and Pat undefined fixed

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-monitoring/crc-report/crc-report.component.css
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/school-monitoring/crc-report/crc-report.component.html

Infra composite table alignment fixed

Infra composite table alignment fixed

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/student-attendance/student-attendance.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/attendance/teacher-attendance/teacher-attendance.component.ts

Added UID for SAT and PAT reports for telemetry

Added UID for SAT and PAT reports for telemetry

---

development/node_api/admin_api/server-side/src/api/controller/configurable-data/list_datasource.js
development/node_api/admin_api/server-side/src/api/router.js
development/ui/admin_ui/client-side/src/app/app.module.ts
development/ui/admin_ui/client-side/src/app/components/diksha-config/diksha-config.component.css
development/ui/admin_ui/client-side/src/app/components/diksha-config/diksha-config.component.html
development/ui/admin_ui/client-side/src/app/components/diksha-config/diksha-config.component.ts
development/ui/admin_ui/client-side/src/app/dashboard/dashboard.component.html
development/ui/admin_ui/client-side/src/app/home/home.component.html
development/ui/admin_ui/client-side/src/app/services/configurable.data.service.ts

Listing .sql files and passing as parameter to nifi functionaly added

Listing .sql files and passing as parameter to nifi functionaly added

---

workflow_deploy/ansible/install.yml
workflow_deploy/ansible/roles/angular_admin/tasks/configure_node.yml
workflow_deploy/ansible/roles/configurable/tasks/main.yml
workflow_deploy/ansible/roles/configurable/tasks/nifi_configurable.yml
workflow_deploy/ansible/roles/configurable/templates/datasource.csv.j2
workflow_deploy/ansible/roles/configurable/vars/main.yml
workflow_deploy/ansible/roles/nifi_params/templates/transaction_and_aggregation_parameters.json.j2
workflow_deploy/ansible/roles/nifi_params/templates/validate_datasource_parameters.json.j2
workflow_deploy/ansible/roles/python_flask/templates/properties_nifi_deploy.py.j2
workflow_deploy/ansible/roles/transaction_and_aggregation/tasks/main.yml
workflow_deploy/ansible/roles/transaction_and_aggregation/tasks/nifi_transaction_and_aggregation.yml
workflow_deploy/ansible/roles/transaction_and_aggregation/templates/datasource.csv.j2
workflow_deploy/ansible/roles/transaction_and_aggregation/vars/main.yml
workflow_deploy/ansible/roles/validate/tasks/main.yml
workflow_deploy/ansible/roles/validate/tasks/nifi_validate.yml
workflow_deploy/ansible/roles/validate/templates/datasource.csv.j2
workflow_deploy/ansible/roles/validate/vars/main.yml
workflow_deploy/ansible/upgrade.yml
workflow_deploy/education_usecase/datasource_config.yml

ansible changes for configurable datasource

---

workflow_deploy/ansible/roles/nifi_install/tasks/install_nifi.yml
workflow_deploy/ansible/roles/nifi_params/tasks/main.yml
workflow_deploy/ansible/roles/python_flask/tasks/configure_flask.yml
workflow_deploy/ansible/roles/python_flask/templates/properties_nifi_deploy.py.j2

added new data sources and nifi_properties file

added new data sources and nifi_properties file

---

workflow_deploy/ansible/roles/python_flask/templates/properties_nifi_deploy.py.j2
workflow_deploy/ansible/roles/transaction_and_aggregation/tasks/nifi_transaction_and_aggregation.yml

updated nifi properties file

---

development/ui/admin_ui/client-side/src/app/app.module.ts

build error fixed

---

development/node_api/admin_api/server-side/src/api/controller/configurable-data/list_datasource.js

Read Directory error fixed

---

development/node_api/dashboard_api/server-side/src/api/controller/commonRoutes/blockWise.js
development/node_api/dashboard_api/server-side/src/api/controller/commonRoutes/clusterWise.js
development/node_api/dashboard_api/server-side/src/api/controller/commonRoutes/districtWise.js
development/node_api/dashboard_api/server-side/src/api/controller/commonRoutes/dropDownMeta.js
development/node_api/dashboard_api/server-side/src/api/controller/commonRoutes/schoolWise.js
development/node_api/dashboard_api/server-side/src/api/router.js
development/ui/admin_ui/client-side/src/app/components/users/change-password/change-password.component.ts
development/ui/admin_ui/client-side/src/environments/environment.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/common-lo-table/common-lo-table.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/common-lo-table/common-lo-table.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/common-map-report/common-map-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/common-map-report/common-map-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/services/dynamic-report.service.ts
development/ui/dashboard_ui/education_usecase/client-side/src/environments/environment.ts

Added Common map report

---

development/node_api/admin_api/server-side/src/api/controller/configurable-data/list_datasource.js
development/node_api/dashboard_api/server-side/src/api/controller/commonRoutes/blockWise.js
development/node_api/dashboard_api/server-side/src/api/controller/commonRoutes/districtWise.js
development/node_api/dashboard_api/server-side/src/api/controller/configurarableProperty/configCardProperty.js
development/node_api/dashboard_api/server-side/src/api/controller/users/logIn.js
development/ui/admin_ui/client-side/src/app/components/nifi-shedular/nifi-shedular.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/config/userStatus.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.css
development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/dynamic-component/dynamic-component.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/dynamic-component/dynamic-component.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/common-lo-table/common-lo-table.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/common-map-report/common-map-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/common-map-report/common-map-report.component.ts

bugs fixed for 3.7

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.css

Adjusted side menu hight

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/dashboards/group-dashboards/dynamic-component/dynamic-component.component.ts

Added loader for dynamic cards

Added loader for dynamic cards

---

development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/common-lo-table/common-lo-table.component.css
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/common-lo-table/common-lo-table.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/common-map-report/common-map-report.component.ts

Bug fixed for lo table

---

development/ui/admin_ui/client-side/src/app/components/diksha-config/diksha-config.component.ts
development/ui/admin_ui/client-side/src/app/home/home.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/containers/home/home.component.html

Added Release date and version

Added Release date and version

---

development/node_api/dashboard_api/server-side/src/api/controller/commonRoutes/blockWise.js
development/node_api/dashboard_api/server-side/src/api/controller/commonRoutes/clusterWise.js
development/node_api/dashboard_api/server-side/src/api/controller/commonRoutes/districtWise.js
development/node_api/dashboard_api/server-side/src/api/controller/commonRoutes/schoolWise.js
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/common-lo-table/common-lo-table.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/common-lo-table/common-lo-table.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/common-map-report/common-map-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/common-map-report/common-map-report.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/student-performance/pat-lo-table/pat-lo-table.component.ts

lo table bug fixed

---

development/ui/admin_ui/client-side/src/app/components/diksha-config/diksha-config.component.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/app.service.ts
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/common-map-report/common-map-report.component.html
development/ui/dashboard_ui/education_usecase/client-side/src/app/reports/common-map-report/common-map-report.component.ts

Map legend color adjusted

---

development/node_api/admin_api/server-side/src/api/controller/configurable-data/list_datasource.js
development/node_api/admin_api/server-side/src/api/controller/niFiScheduler/newDataSource.js
development/node_api/admin_api/server-side/src/api/lib/db.js
development/node_api/admin_api/server-side/src/api/router.js
development/ui/admin_ui/client-side/src/app/components/nifi-shedular/nifi-shedular.component.html
development/ui/admin_ui/client-side/src/app/components/nifi-shedular/nifi-shedular.component.ts
development/ui/admin_ui/client-side/src/app/keycloak-security.service.ts
development/ui/admin_ui/client-side/src/app/services/nifi-shedular.service.ts

Added new data scorce in scheduler list

Added new data scorce in scheduler list

---

development/node_api/admin_api/server-side/src/api/controller/configurable-data/list_datasource.js
development/node_api/admin_api/server-side/src/api/controller/niFiScheduler/newDataSource.js
development/node_api/admin_api/server-side/src/api/lib/db.js
development/ui/admin_ui/client-side/src/app/components/nifi-shedular/nifi-shedular.component.html
development/ui/admin_ui/client-side/src/app/components/nifi-shedular/nifi-shedular.component.ts

Scheduler bug fixed

---

development/node_api/admin_api/server-side/src/api/controller/configurable-data/list_datasource.js
development/node_api/admin_api/server-side/src/api/controller/niFiScheduler/restartSchedular.js

Schedular and .sql dropdown fixed

Schedular and .sql dropdown fixed

---

development/node_api/admin_api/server-side/src/api/controller/niFiScheduler/newDataSource.js
development/node_api/admin_api/server-side/src/api/controller/niFiScheduler/restartSchedular.js

Remove validation and transation processors from rescheduler

Remove validation and transation processors from rescheduler
